# Generated by Django 4.0.3 on 2022-04-07 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_thread_snippet_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
