# Generated by Django 4.0.3 on 2022-04-08 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_comment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='image',
        ),
        migrations.AlterField(
            model_name='thread',
            name='tags',
            field=models.ManyToManyField(blank=True, to='app.tag'),
        ),
    ]
